# RTX 30 series — canonical list for methodology test.
# TPU IDs verified via websearch snippets (techpowerup.com/gpu-specs).
# SHS slugs verified via https://secondhandsilicon.com/api/search?q=3090 etc.
#
# RTX 20 series — added second. TPU IDs read live from the GPU Database table
# via headed Chromium (playwright-cli); SHS slugs via /api/search.

GPUS = [
    {
        "id": "rtx-3090-ti",
        "name": "NVIDIA GeForce RTX 3090 Ti",
        "short_name": "RTX 3090 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3090-ti.c3829",
        "tpu_id": "c3829",
        "shs_slug": "nvidia-rtx-3090-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3090-ti",
    },
    {
        "id": "rtx-3090",
        "name": "NVIDIA GeForce RTX 3090",
        "short_name": "RTX 3090",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3090.c3622",
        "tpu_id": "c3622",
        "shs_slug": "nvidia-rtx-3090",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3090",
    },
    {
        "id": "rtx-3080-ti",
        "name": "NVIDIA GeForce RTX 3080 Ti",
        "short_name": "RTX 3080 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3080-ti.c3735",
        "tpu_id": "c3735",
        "shs_slug": "nvidia-rtx-3080-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3080-ti",
    },
    {
        "id": "rtx-3080-12gb",
        "name": "NVIDIA GeForce RTX 3080 12GB",
        "short_name": "RTX 3080 12GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3080-12-gb.c3834",
        "tpu_id": "c3834",
        "shs_slug": "nvidia-rtx-3080-12gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3080-12gb",
    },
    {
        "id": "rtx-3080-10gb",
        "name": "NVIDIA GeForce RTX 3080 10GB",
        "short_name": "RTX 3080 10GB",
        "relperf_name": "GeForce RTX 3080",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3080.c3621",
        "tpu_id": "c3621",
        "shs_slug": "nvidia-rtx-3080-10gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3080-10gb",
    },
    {
        "id": "rtx-3070-ti",
        "name": "NVIDIA GeForce RTX 3070 Ti",
        "short_name": "RTX 3070 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3070-ti.c3675",
        "tpu_id": "c3675",
        "shs_slug": "nvidia-rtx-3070-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3070-ti",
    },
    {
        "id": "rtx-3070",
        "name": "NVIDIA GeForce RTX 3070",
        "short_name": "RTX 3070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3070.c3674",
        "tpu_id": "c3674",
        "shs_slug": "nvidia-rtx-3070",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3070",
    },
    {
        "id": "rtx-3060-ti",
        "name": "NVIDIA GeForce RTX 3060 Ti",
        "short_name": "RTX 3060 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3060-ti.c3681",
        "tpu_id": "c3681",
        "shs_slug": "nvidia-rtx-3060-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3060-ti",
    },
    {
        "id": "rtx-3060-12gb",
        "name": "NVIDIA GeForce RTX 3060 12GB",
        "short_name": "RTX 3060 12GB",
        "relperf_name": "GeForce RTX 3060 12 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3060-12-gb.c3682",
        "tpu_id": "c3682",
        "shs_slug": "nvidia-rtx-3060-12gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3060-12gb",
    },
    {
        "id": "rtx-3060-8gb",
        "name": "NVIDIA GeForce RTX 3060 8GB",
        "short_name": "RTX 3060 8GB",
        # NO reference page exists on TPU (verified live 2026-09-06 via the GPU
        # Database table: only 3060 12GB / Ti are listed; the 8GB was a quiet
        # AIB-only launch). Specs inherit the 3060 12GB reference (same die,
        # clocks, core config); memory subsystem (8GB/128-bit/240GB/s) per TPU
        # news post https://www.techpowerup.com/300248/...
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "nvidia-rtx-3060-8gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3060-8gb",
    },
    {
        "id": "rtx-3050-8gb",
        "name": "NVIDIA GeForce RTX 3050 8GB",
        "short_name": "RTX 3050 8GB",
        "relperf_name": "GeForce RTX 3050 8 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-3050-8-gb.c3858",
        "tpu_id": "c3858",
        "shs_slug": "nvidia-rtx-3050",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-3050",
    },
    # ---- RTX 20 series (Turing; PCIe 3.0; 2nd-gen Tensor, no FP4/FP8) ----
    {
        "id": "rtx-2080-ti",
        "name": "NVIDIA GeForce RTX 2080 Ti",
        "short_name": "RTX 2080 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2080-ti.c3305",
        "tpu_id": "c3305",
        "shs_slug": "nvidia-rtx-2080-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2080-ti",
    },
    {
        "id": "rtx-2080-super",
        "name": "NVIDIA GeForce RTX 2080 Super",
        "short_name": "RTX 2080 Super",
        "relperf_name": "GeForce RTX 2080 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2080-super.c3439",
        "tpu_id": "c3439",
        "shs_slug": "nvidia-rtx-2080-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2080-super",
    },
    {
        "id": "rtx-2080",
        "name": "NVIDIA GeForce RTX 2080",
        "short_name": "RTX 2080",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2080.c3224",
        "tpu_id": "c3224",
        "shs_slug": "nvidia-rtx-2080",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2080",
    },
    {
        "id": "rtx-2070-super",
        "name": "NVIDIA GeForce RTX 2070 Super",
        "short_name": "RTX 2070 Super",
        "relperf_name": "GeForce RTX 2070 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2070-super.c3440",
        "tpu_id": "c3440",
        "shs_slug": "nvidia-rtx-2070-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2070-super",
    },
    {
        "id": "rtx-2070",
        "name": "NVIDIA GeForce RTX 2070",
        "short_name": "RTX 2070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2070.c3252",
        "tpu_id": "c3252",
        "shs_slug": "nvidia-rtx-2070",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2070",
    },
    {
        "id": "rtx-2060-super",
        "name": "NVIDIA GeForce RTX 2060 Super",
        "short_name": "RTX 2060 Super",
        "relperf_name": "GeForce RTX 2060 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2060-super.c3441",
        "tpu_id": "c3441",
        "shs_slug": "nvidia-rtx-2060-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2060-super",
    },
    {
        "id": "rtx-2060-6gb",
        "name": "NVIDIA GeForce RTX 2060 6GB",
        "short_name": "RTX 2060 6GB",
        "relperf_name": "GeForce RTX 2060",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-2060.c3310",
        "tpu_id": "c3310",
        "shs_slug": "nvidia-rtx-2060-6gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2060-6gb",
    },
    {
        "id": "rtx-2060-12gb",
        "name": "NVIDIA GeForce RTX 2060 12GB",
        "short_name": "RTX 2060 12GB",
        # NO reference page exists on TPU (verified live 2026-09-06 via the GPU
        # Database table: only 2060 6GB / Super are listed; the 12GB was a
        # quiet AIB-only refresh). Inherits the 2060 6GB reference die data;
        # core config + memory per contemporary coverage (2176 CUDA / 12GB /
        # 192-bit); MSRP uncertain (no official figure; SHS base $349).
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "nvidia-rtx-2060-12gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-2060-12gb",
    },
    # ---- RTX 40 series (Ada Lovelace; 4N; FP8, no FP4 -> INT4 wins) ----
    # TPU IDs read live from the GPU Database table 2026-09-06; SHS slugs via
    # /api/search. 4060 Ti SHS slug aggregates 8GB+16GB (single slug); TPU ref
    # is the 8GB launch page.
    {
        "id": "rtx-4090",
        "name": "NVIDIA GeForce RTX 4090",
        "short_name": "RTX 4090",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4090.c3889",
        "tpu_id": "c3889",
        "shs_slug": "nvidia-rtx-4090",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4090",
    },
    {
        "id": "rtx-4080",
        "name": "NVIDIA GeForce RTX 4080",
        "short_name": "RTX 4080",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4080.c3888",
        "tpu_id": "c3888",
        "shs_slug": "nvidia-rtx-4080",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4080",
    },
    {
        "id": "rtx-4080-super",
        "name": "NVIDIA GeForce RTX 4080 Super",
        "short_name": "RTX 4080 Super",
        "relperf_name": "GeForce RTX 4080 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4080-super.c4182",
        "tpu_id": "c4182",
        "shs_slug": "nvidia-rtx-4080-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4080-super",
    },
    {
        "id": "rtx-4070-ti",
        "name": "NVIDIA GeForce RTX 4070 Ti",
        "short_name": "RTX 4070 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4070-ti.c3950",
        "tpu_id": "c3950",
        "shs_slug": "nvidia-rtx-4070-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4070-ti",
    },
    {
        "id": "rtx-4070-ti-super",
        "name": "NVIDIA GeForce RTX 4070 Ti Super",
        "short_name": "RTX 4070 Ti Super",
        "relperf_name": "GeForce RTX 4070 Ti SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4070-ti-super.c4187",
        "tpu_id": "c4187",
        "shs_slug": "nvidia-rtx-4070-ti-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4070-ti-super",
    },
    {
        "id": "rtx-4070-super",
        "name": "NVIDIA GeForce RTX 4070 Super",
        "short_name": "RTX 4070 Super",
        "relperf_name": "GeForce RTX 4070 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4070-super.c4186",
        "tpu_id": "c4186",
        "shs_slug": "nvidia-rtx-4070-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4070-super",
    },
    {
        "id": "rtx-4070",
        "name": "NVIDIA GeForce RTX 4070",
        "short_name": "RTX 4070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4070.c3924",
        "tpu_id": "c3924",
        "shs_slug": "nvidia-rtx-4070",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4070",
    },
    {
        "id": "rtx-4060-ti",
        "name": "NVIDIA GeForce RTX 4060 Ti",
        "short_name": "RTX 4060 Ti",
        "relperf_name": "GeForce RTX 4060 Ti 8 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4060-ti-8-gb.c3890",
        "tpu_id": "c3890",
        "shs_slug": "nvidia-rtx-4060-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4060-ti",
    },
    {
        "id": "rtx-4060",
        "name": "NVIDIA GeForce RTX 4060",
        "short_name": "RTX 4060",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-4060.c4107",
        "tpu_id": "c4107",
        "shs_slug": "nvidia-rtx-4060",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-4060",
    },
    # ---- RTX 50 series (Blackwell 2.0; FP4 max, no INT4 row on TPU) ----
    # 5060 Ti SHS slug aggregates 8GB+16GB; TPU ref is the 8GB page (16GB:
    # geforce-rtx-5060-ti-16-gb.c4292, same die). RTX 5050 has no SHS slug
    # (strict rule: out until price coverage exists).
    {
        "id": "rtx-5090",
        "name": "NVIDIA GeForce RTX 5090",
        "short_name": "RTX 5090",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5090.c4216",
        "tpu_id": "c4216",
        "shs_slug": "nvidia-rtx-5090",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5090",
    },
    {
        "id": "rtx-5080",
        "name": "NVIDIA GeForce RTX 5080",
        "short_name": "RTX 5080",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5080.c4217",
        "tpu_id": "c4217",
        "shs_slug": "nvidia-rtx-5080",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5080",
    },
    {
        "id": "rtx-5070-ti",
        "name": "NVIDIA GeForce RTX 5070 Ti",
        "short_name": "RTX 5070 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5070-ti.c4243",
        "tpu_id": "c4243",
        "shs_slug": "nvidia-rtx-5070-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5070-ti",
    },
    {
        "id": "rtx-5070",
        "name": "NVIDIA GeForce RTX 5070",
        "short_name": "RTX 5070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5070.c4218",
        "tpu_id": "c4218",
        "shs_slug": "nvidia-rtx-5070",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5070",
    },
    {
        "id": "rtx-5060-ti",
        "name": "NVIDIA GeForce RTX 5060 Ti",
        "short_name": "RTX 5060 Ti",
        "relperf_name": "GeForce RTX 5060 Ti 8 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5060-ti-8-gb.c4246",
        "tpu_id": "c4246",
        "shs_slug": "nvidia-rtx-5060-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5060-ti",
    },
    {
        "id": "rtx-5060",
        "name": "NVIDIA GeForce RTX 5060",
        "short_name": "RTX 5060",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-rtx-5060.c4219",
        "tpu_id": "c4219",
        "shs_slug": "nvidia-rtx-5060",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-rtx-5060",
    },
    # ---- GTX 16/10 series (Pascal/Turing-GTX; no Tensor cores -> Theoretical
    # fallback). TPU IDs read live from the GPU Database table 2026-09-06.
    # GTX 1060 3GB has no TPU reference page (table lists 6GB only); sibling
    # of the 6GB card (GP106, 1152 CUDA / 3GB / 192-bit per NVIDIA specs).
    {
        "id": "gtx-1080-ti",
        "name": "NVIDIA GeForce GTX 1080 Ti",
        "short_name": "GTX 1080 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1080-ti.c2877",
        "tpu_id": "c2877",
        "shs_slug": "nvidia-gtx-1080-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1080-ti",
    },
    {
        "id": "gtx-1080",
        "name": "NVIDIA GeForce GTX 1080",
        "short_name": "GTX 1080",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1080.c2839",
        "tpu_id": "c2839",
        "shs_slug": "nvidia-gtx-1080",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1080",
    },
    {
        "id": "gtx-1070-ti",
        "name": "NVIDIA GeForce GTX 1070 Ti",
        "short_name": "GTX 1070 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1070-ti.c3010",
        "tpu_id": "c3010",
        "shs_slug": "nvidia-gtx-1070-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1070-ti",
    },
    {
        "id": "gtx-1070",
        "name": "NVIDIA GeForce GTX 1070",
        "short_name": "GTX 1070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1070.c2840",
        "tpu_id": "c2840",
        "shs_slug": "nvidia-gtx-1070",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1070",
    },
    {
        "id": "gtx-1060-6gb",
        "name": "NVIDIA GeForce GTX 1060 6GB",
        "short_name": "GTX 1060 6GB",
        "relperf_name": "GeForce GTX 1060 6 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1060-6-gb.c2862",
        "tpu_id": "c2862",
        "shs_slug": "nvidia-gtx-1060-6gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1060-6gb",
    },
    {
        "id": "gtx-1060-3gb",
        "name": "NVIDIA GeForce GTX 1060 3GB",
        "short_name": "GTX 1060 3GB",
        # NO reference page on TPU (table lists 6GB only). Sibling of the 6GB
        # card: GP106-300 (1152 CUDA / 72 TMU / 48 ROP), 3GB GDDR5 192-bit;
        # clocks/MSRP per NVIDIA launch specs ($199). No relperf attribution.
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "nvidia-gtx-1060-3gb",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1060-3gb",
    },
    {
        "id": "gtx-1050",
        "name": "NVIDIA GeForce GTX 1050",
        "short_name": "GTX 1050",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1050.c2875",
        "tpu_id": "c2875",
        "shs_slug": "nvidia-gtx-1050",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1050",
    },
    {
        "id": "gtx-1660-ti",
        "name": "NVIDIA GeForce GTX 1660 Ti",
        "short_name": "GTX 1660 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1660-ti.c3364",
        "tpu_id": "c3364",
        "shs_slug": "nvidia-gtx-1660-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1660-ti",
    },
    {
        "id": "gtx-1660-super",
        "name": "NVIDIA GeForce GTX 1660 Super",
        "short_name": "GTX 1660 Super",
        "relperf_name": "GeForce GTX 1660 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1660-super.c3458",
        "tpu_id": "c3458",
        "shs_slug": "nvidia-gtx-1660-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1660-super",
    },
    {
        "id": "gtx-1660",
        "name": "NVIDIA GeForce GTX 1660",
        "short_name": "GTX 1660",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1660.c3365",
        "tpu_id": "c3365",
        "shs_slug": "nvidia-gtx-1660",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1660",
    },
    {
        "id": "gtx-1650-super",
        "name": "NVIDIA GeForce GTX 1650 Super",
        "short_name": "GTX 1650 Super",
        "relperf_name": "GeForce GTX 1650 SUPER",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1650-super.c3411",
        "tpu_id": "c3411",
        "shs_slug": "nvidia-gtx-1650-super",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1650-super",
    },
    {
        "id": "gtx-1650",
        "name": "NVIDIA GeForce GTX 1650",
        "short_name": "GTX 1650",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-1650.c3366",
        "tpu_id": "c3366",
        "shs_slug": "nvidia-gtx-1650",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-1650",
    },
    # ---- Radeon RX 5000/6000/7000/9000 (RDNA 1-4). TPU IDs read live from the
    # GPU Database table 2026-09-06; SHS slugs via /api/search. RX 6700 has no
    # TPU reference page (table lists XT only); sibling of the 6700 XT.
    {
        "id": "rx-5700",
        "name": "AMD Radeon RX 5700",
        "short_name": "RX 5700",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-5700.c3437",
        "tpu_id": "c3437",
        "shs_slug": "amd-rx-5700",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-5700",
    },
    {
        "id": "rx-5700-xt",
        "name": "AMD Radeon RX 5700 XT",
        "short_name": "RX 5700 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-5700-xt.c3339",
        "tpu_id": "c3339",
        "shs_slug": "amd-rx-5700-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-5700-xt",
    },
    {
        "id": "rx-6600",
        "name": "AMD Radeon RX 6600",
        "short_name": "RX 6600",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6600.c3696",
        "tpu_id": "c3696",
        "shs_slug": "amd-rx-6600",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6600",
    },
    {
        "id": "rx-6700",
        "name": "AMD Radeon RX 6700",
        "short_name": "RX 6700",
        # NO reference page on TPU (table lists 6700 XT only; quiet launch).
        # Sibling of the 6700 XT (Navi 22, 17.2B/335mm²): 2304 SP / 36 CU /
        # 10GB GDDR6 160-bit per AMD specs; launch date uncertain (None).
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "amd-rx-6700",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6700",
    },
    {
        "id": "rx-6800",
        "name": "AMD Radeon RX 6800",
        "short_name": "RX 6800",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6800.c3713",
        "tpu_id": "c3713",
        "shs_slug": "amd-rx-6800",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6800",
    },
    {
        "id": "rx-6950-xt",
        "name": "AMD Radeon RX 6950 XT",
        "short_name": "RX 6950 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6950-xt.c3875",
        "tpu_id": "c3875",
        "shs_slug": "amd-rx-6950-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6950-xt",
    },
    {
        "id": "rx-7600",
        "name": "AMD Radeon RX 7600",
        "short_name": "RX 7600",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7600.c4153",
        "tpu_id": "c4153",
        "shs_slug": "amd-rx-7600",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7600",
    },
    {
        "id": "rx-7600-xt",
        "name": "AMD Radeon RX 7600 XT",
        "short_name": "RX 7600 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7600-xt.c4190",
        "tpu_id": "c4190",
        "shs_slug": "amd-rx-7600-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7600-xt",
    },
    {
        "id": "rx-7700-xt",
        "name": "AMD Radeon RX 7700 XT",
        "short_name": "RX 7700 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7700-xt.c3911",
        "tpu_id": "c3911",
        "shs_slug": "amd-rx-7700-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7700-xt",
    },
    {
        "id": "rx-7800-xt",
        "name": "AMD Radeon RX 7800 XT",
        "short_name": "RX 7800 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7800-xt.c3839",
        "tpu_id": "c3839",
        "shs_slug": "amd-rx-7800-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7800-xt",
    },
    {
        "id": "rx-7900-gre",
        "name": "AMD Radeon RX 7900 GRE",
        "short_name": "RX 7900 GRE",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7900-gre.c4166",
        "tpu_id": "c4166",
        "shs_slug": "amd-rx-7900-gre",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7900-gre",
    },
    {
        "id": "rx-7900-xt",
        "name": "AMD Radeon RX 7900 XT",
        "short_name": "RX 7900 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7900-xt.c3912",
        "tpu_id": "c3912",
        "shs_slug": "amd-rx-7900-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7900-xt",
    },
    {
        "id": "rx-7900-xtx",
        "name": "AMD Radeon RX 7900 XTX",
        "short_name": "RX 7900 XTX",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-7900-xtx.c3941",
        "tpu_id": "c3941",
        "shs_slug": "amd-rx-7900-xtx",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-7900-xtx",
    },
    {
        "id": "rx-9070",
        "name": "AMD Radeon RX 9070",
        "short_name": "RX 9070",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-9070.c4250",
        "tpu_id": "c4250",
        "shs_slug": "radeon-rx-9070",
        "shs_url": "https://secondhandsilicon.com/product/radeon-rx-9070",
    },
    {
        "id": "rx-9070-xt",
        "name": "AMD Radeon RX 9070 XT",
        "short_name": "RX 9070 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-9070-xt.c4229",
        "tpu_id": "c4229",
        "shs_slug": "radeon-rx-9070-xt",
        "shs_url": "https://secondhandsilicon.com/product/radeon-rx-9070-xt",
    },
    # ---- Radeon RX 400/500 + Fury (GCN; no Matrix -> Theoretical fallback).
    # TPU IDs via live table (550/570/580/590) + websearch snippets
    # (460/480/560/6400/Fury X). 4GB/8GB variants share one TPU reference
    # page each (like RTX 4060 Ti precedent, inverted: separate SHS slugs).
    # R9 Fury (non-X) has no reference page; sibling of Fury X.
    {
        "id": "rx-460",
        "name": "AMD Radeon RX 460",
        "short_name": "RX 460",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-460.c2849",
        "tpu_id": "c2849",
        "shs_slug": "amd-rx-460",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-460",
    },
    {
        "id": "rx-480-8gb",
        "name": "AMD Radeon RX 480 8GB",
        "short_name": "RX 480 8GB",
        "relperf_name": "Radeon RX 480",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-480.c2848",
        "tpu_id": "c2848",
        # TPU lists $229; AMD launch MSRP was $239 (8GB).
        "tpu_overrides": {"launch_price_usd": 239},
        "shs_slug": "amd-rx-480-8gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-480-8gb",
    },
    {
        "id": "rx-480-4gb",
        "name": "AMD Radeon RX 480 4GB",
        "short_name": "RX 480 4GB",
        "relperf_name": "Radeon RX 480",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-480.c2848",
        "tpu_id": "c2848",
        # 4GB variant on the 8GB reference page ($199 launch).
        "tpu_overrides": {"memory_size_gb": 4, "launch_price_usd": 199},
        "shs_slug": "amd-rx-480-4gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-480-4gb",
    },
    {
        "id": "rx-550",
        "name": "AMD Radeon RX 550",
        "short_name": "RX 550",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-550.c2947",
        "tpu_id": "c2947",
        "shs_slug": "amd-rx-550",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-550",
    },
    {
        "id": "rx-560",
        "name": "AMD Radeon RX 560",
        "short_name": "RX 560",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-560.c2940",
        "tpu_id": "c2940",
        "shs_slug": "amd-rx-560",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-560",
    },
    {
        "id": "rx-570-8gb",
        "name": "AMD Radeon RX 570 8GB",
        "short_name": "RX 570 8GB",
        "relperf_name": "Radeon RX 570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-570.c2939",
        "tpu_id": "c2939",
        # 8GB variant on the 4GB reference page ($199 launch).
        "tpu_overrides": {"memory_size_gb": 8, "launch_price_usd": 199},
        "shs_slug": "amd-rx-570-8gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-570-8gb",
    },
    {
        "id": "rx-570-4gb",
        "name": "AMD Radeon RX 570 4GB",
        "short_name": "RX 570 4GB",
        "relperf_name": "Radeon RX 570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-570.c2939",
        "tpu_id": "c2939",
        "shs_slug": "amd-rx-570-4gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-570-4gb",
    },
    {
        "id": "rx-580-8gb",
        "name": "AMD Radeon RX 580 8GB",
        "short_name": "RX 580 8GB",
        "relperf_name": "Radeon RX 580",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-580.c2938",
        "tpu_id": "c2938",
        "shs_slug": "amd-rx-580-8gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-580-8gb",
    },
    {
        "id": "rx-580-4gb",
        "name": "AMD Radeon RX 580 4GB",
        "short_name": "RX 580 4GB",
        "relperf_name": "Radeon RX 580",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-580.c2938",
        "tpu_id": "c2938",
        # 4GB variant on the 8GB reference page ($199 launch).
        "tpu_overrides": {"memory_size_gb": 4, "launch_price_usd": 199},
        "shs_slug": "amd-rx-580-4gb",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-580-4gb",
    },
    {
        "id": "rx-590",
        "name": "AMD Radeon RX 590",
        "short_name": "RX 590",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-590.c3322",
        "tpu_id": "c3322",
        "shs_slug": "amd-rx-590",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-590",
    },
    {
        "id": "rx-6400",
        "name": "AMD Radeon RX 6400",
        "short_name": "RX 6400",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6400.c3813",
        "tpu_id": "c3813",
        "shs_slug": "amd-rx-6400",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6400",
    },
    {
        "id": "rx-5300",
        "name": "AMD Radeon RX 5300",
        "short_name": "RX 5300",
        # OEM-only card; TPU reference is the OEM page.
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-5300-oem.c3584",
        "tpu_id": "c3584",
        "shs_slug": "radeon-rx-5300",
        "shs_url": "https://secondhandsilicon.com/product/radeon-rx-5300",
    },
    {
        "id": "r9-fury-x",
        "name": "AMD Radeon R9 Fury X",
        "short_name": "R9 Fury X",
        "relperf_name": "Radeon R9 FURY X",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-fury-x.c2677",
        "tpu_id": "c2677",
        "shs_slug": "amd-r9-fury-x",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-fury-x",
    },
    {
        "id": "r9-fury",
        "name": "AMD Radeon R9 Fury",
        "short_name": "R9 Fury",
        "relperf_name": "Radeon R9 FURY",
        # NO reference page on TPU (only AIB b-series pages found); sibling
        # of Fury X (Fiji PRO, 3584 SP / 1000 MHz / 4GB HBM per AMD specs).
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "amd-r9-fury",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-fury",
    },
    # ---- Intel Arc Alchemist/Battlemage (Xe-HPG/Xe2-HPG; XMX INT4 wins).
    # TPU IDs via live table (B580) + websearch snippets. A310 has no TPU
    # reference page (quiet OEM/SI launch); sibling of the A380.
    {
        "id": "arc-a770",
        "name": "Intel Arc A770",
        "short_name": "Arc A770",
        # TPU reference is the 16GB card; SHS slug may mix 8GB listings
        # (titles archived for later variant splits).
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-a770.c3914",
        "tpu_id": "c3914",
        "shs_slug": "intel-arc-a770",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-a770",
    },
    {
        "id": "arc-a750",
        "name": "Intel Arc A750",
        "short_name": "Arc A750",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-a750.c3929",
        "tpu_id": "c3929",
        "shs_slug": "intel-arc-a750",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-a750",
    },
    {
        "id": "arc-a580",
        "name": "Intel Arc A580",
        "short_name": "Arc A580",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-a580.c3928",
        "tpu_id": "c3928",
        "shs_slug": "intel-arc-a580",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-a580",
    },
    {
        "id": "arc-a380",
        "name": "Intel Arc A380",
        "short_name": "Arc A380",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-a380.c3913",
        "tpu_id": "c3913",
        "shs_slug": "intel-arc-a380",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-a380",
    },
    {
        "id": "arc-a310",
        "name": "Intel Arc A310",
        "short_name": "Arc A310",
        # NO reference page on TPU; DG2-128 sibling of the A380 (768 SP /
        # 6 Xe / 4GB 64-bit / 75W per Intel specs). No official MSRP ($89
        # matches SHS base). Flagged, not verified live.
        "tpu_url": None,
        "tpu_id": None,
        "shs_slug": "intel-arc-a310",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-a310",
    },
    {
        "id": "arc-b580",
        "name": "Intel Arc B580",
        "short_name": "Arc B580",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-b580.c4244",
        "tpu_id": "c4244",
        "shs_slug": "intel-arc-b580",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-b580",
    },
    {
        "id": "arc-b570",
        "name": "Intel Arc B570",
        "short_name": "Arc B570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/arc-b570.c4245",
        "tpu_id": "c4245",
        "shs_slug": "intel-arc-b570",
        "shs_url": "https://secondhandsilicon.com/product/intel-arc-b570",
    },
    # ---- Workstation Ampere (RTX Ax000). TPU IDs via websearch snippets.
    {
        "id": "rtx-a4000",
        "name": "NVIDIA RTX A4000",
        "short_name": "RTX A4000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/rtx-a4000.c3756",
        "tpu_id": "c3756",
        "shs_slug": "rtx-a4000",
        "shs_url": "https://secondhandsilicon.com/product/rtx-a4000",
    },
    {
        "id": "rtx-a5000",
        "name": "NVIDIA RTX A5000",
        "short_name": "RTX A5000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/rtx-a5000.c3748",
        "tpu_id": "c3748",
        "shs_slug": "rtx-a5000",
        "shs_url": "https://secondhandsilicon.com/product/rtx-a5000",
    },
    {
        "id": "rtx-a6000",
        "name": "NVIDIA RTX A6000",
        "short_name": "RTX A6000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/rtx-a6000.c3686",
        "tpu_id": "c3686",
        "shs_slug": "rtx-a6000",
        "shs_url": "https://secondhandsilicon.com/product/rtx-a6000",
    },
    # ---- Workstation Turing (Quadro RTX).
    {
        "id": "quadro-rtx-4000",
        "name": "NVIDIA Quadro RTX 4000",
        "short_name": "Quadro RTX 4000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-rtx-4000.c3336",
        "tpu_id": "c3336",
        "shs_slug": "quadro-rtx-4000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-rtx-4000",
    },
    {
        "id": "quadro-rtx-6000",
        "name": "NVIDIA Quadro RTX 6000",
        "short_name": "Quadro RTX 6000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-rtx-6000.c3307",
        "tpu_id": "c3307",
        "shs_slug": "quadro-rtx-6000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-rtx-6000",
    },
    # ---- Datacenter (Tesla/A100). Reference pages are the PCIe cards; SHS
    # slugs may mix memory variants (titles archived for later splits).
    # P100 ref is the 16GB card, V100 the 32GB, A100 the 40GB.
    {
        "id": "tesla-p100",
        "name": "NVIDIA Tesla P100",
        "short_name": "Tesla P100",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/tesla-p100-pcie-16-gb.c2888",
        "tpu_id": "c2888",
        "shs_slug": "tesla-p100",
        "shs_url": "https://secondhandsilicon.com/product/tesla-p100",
    },
    {
        "id": "tesla-v100",
        "name": "NVIDIA Tesla V100",
        "short_name": "Tesla V100",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/tesla-v100-pcie-32-gb.c3184",
        "tpu_id": "c3184",
        "shs_slug": "tesla-v100",
        "shs_url": "https://secondhandsilicon.com/product/tesla-v100",
    },
    {
        "id": "tesla-a100",
        "name": "NVIDIA Tesla A100",
        "short_name": "Tesla A100",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/a100-pcie-40-gb.c3623",
        "tpu_id": "c3623",
        "shs_slug": "tesla-a100",
        "shs_url": "https://secondhandsilicon.com/product/tesla-a100",
    },
    # ---- Workstation RDNA 3 (Radeon Pro). Ref is the 32GB card.
    {
        "id": "radeon-pro-w7800",
        "name": "AMD Radeon Pro W7800",
        "short_name": "Radeon Pro W7800",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-pro-w7800.c4148",
        "tpu_id": "c4148",
        "shs_slug": "radeon-pro-w7800",
        "shs_url": "https://secondhandsilicon.com/product/radeon-pro-w7800",
    },
    # ---- GTX 400/500 (Fermi; no boost clocks on TPU -> base/boost None).
    {
        "id": "gtx-480",
        "name": "NVIDIA GeForce GTX 480",
        "short_name": "GTX 480",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-480.c268",
        "tpu_id": "c268",
        "shs_slug": "nvidia-gtx-480",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-480",
    },
    {
        "id": "gtx-570",
        "name": "NVIDIA GeForce GTX 570",
        "short_name": "GTX 570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-570.c269",
        "tpu_id": "c269",
        "shs_slug": "nvidia-gtx-570",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-570",
    },
    # ---- GTX 600 (Kepler; dual-GPU 690 carries board-level specs, see
    # curated note + METHODOLOGY dual-GPU limitation).
    {
        "id": "gtx-680",
        "name": "NVIDIA GeForce GTX 680",
        "short_name": "GTX 680",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-680.c342",
        "tpu_id": "c342",
        "shs_slug": "nvidia-gtx-680",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-680",
    },
    {
        "id": "gtx-690",
        "name": "NVIDIA GeForce GTX 690",
        "short_name": "GTX 690",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-690.c361",
        "tpu_id": "c361",
        # Dual-GPU: TPU reports per-GPU specs; board totals override so the
        # card-level metric matches the card-level price (see METHODOLOGY).
        "tpu_overrides": {"cuda_cores": 3072, "tmu": 256, "rop": 64,
                          "pixel_rate_gpixels": 65.22, "texture_rate_gtexels": 260.8,
                          "theoretical_fp32_tflops": 6.26,
                          "theoretical_fp64_gflops": 260.8,
                          "transistors_b": 7.08, "die_size_mm2": 588,
                          "die": "2x GK104-355-A2", "memory_size_gb": 4},
        "shs_slug": "nvidia-gtx-690",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-690",
    },
    # ---- GTX 700 (Kepler/Maxwell; Titan Z is dual-GPU, board-level specs).
    {
        "id": "gtx-750",
        "name": "NVIDIA GeForce GTX 750",
        "short_name": "GTX 750",
        # 1GB reference page; 2GB boards share the SHS slug (titles archived).
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-750.c1986",
        "tpu_id": "c1986",
        "shs_slug": "nvidia-gtx-750",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-750",
    },
    {
        "id": "gtx-760",
        "name": "NVIDIA GeForce GTX 760",
        "short_name": "GTX 760",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-760.c1857",
        "tpu_id": "c1857",
        "shs_slug": "nvidia-gtx-760",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-760",
    },
    {
        "id": "gtx-770",
        "name": "NVIDIA GeForce GTX 770",
        "short_name": "GTX 770",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-770.c1856",
        "tpu_id": "c1856",
        "shs_slug": "nvidia-gtx-770",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-770",
    },
    {
        "id": "gtx-780",
        "name": "NVIDIA GeForce GTX 780",
        "short_name": "GTX 780",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-780.c1701",
        "tpu_id": "c1701",
        "shs_slug": "nvidia-gtx-780",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-780",
    },
    {
        "id": "gtx-780-ti",
        "name": "NVIDIA GeForce GTX 780 Ti",
        "short_name": "GTX 780 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-780-ti.c2512",
        "tpu_id": "c2512",
        "shs_slug": "nvidia-gtx-780-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-780-ti",
    },
    # ---- GTX 900 (Maxwell).
    {
        "id": "gtx-950",
        "name": "NVIDIA GeForce GTX 950",
        "short_name": "GTX 950",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-950.c2747",
        "tpu_id": "c2747",
        "shs_slug": "nvidia-gtx-950",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-950",
    },
    {
        "id": "gtx-960",
        "name": "NVIDIA GeForce GTX 960",
        "short_name": "GTX 960",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-960.c2637",
        "tpu_id": "c2637",
        "shs_slug": "nvidia-gtx-960",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-960",
    },
    {
        "id": "gtx-970",
        "name": "NVIDIA GeForce GTX 970",
        "short_name": "GTX 970",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-970.c2620",
        "tpu_id": "c2620",
        "shs_slug": "nvidia-gtx-970",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-970",
    },
    {
        "id": "gtx-980",
        "name": "NVIDIA GeForce GTX 980",
        "short_name": "GTX 980",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-980.c2621",
        "tpu_id": "c2621",
        "shs_slug": "nvidia-gtx-980",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-980",
    },
    {
        "id": "gtx-980-ti",
        "name": "NVIDIA GeForce GTX 980 Ti",
        "short_name": "GTX 980 Ti",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-980-ti.c2724",
        "tpu_id": "c2724",
        "shs_slug": "nvidia-gtx-980-ti",
        "shs_url": "https://secondhandsilicon.com/product/nvidia-gtx-980-ti",
    },
    # ---- Titans (no relperf entries on TPU's table -> null, never guessed).
    # SHS slugs verified via /api/search + product-name check (titan-x is the
    # $999 Maxwell card; TITAN X Pascal has no slug and stays out).
    {
        "id": "titan-kepler",
        "name": "NVIDIA GeForce GTX Titan",
        "short_name": "GTX Titan",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-titan.c1996",
        "tpu_id": "c1996",
        "shs_slug": "geforce-gtx-titan",
        "shs_url": "https://secondhandsilicon.com/product/geforce-gtx-titan",
    },
    {
        "id": "titan-black",
        "name": "NVIDIA GeForce GTX Titan Black",
        "short_name": "GTX Titan Black",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-titan-black.c2549",
        "tpu_id": "c2549",
        "shs_slug": "geforce-gtx-titan-black",
        "shs_url": "https://secondhandsilicon.com/product/geforce-gtx-titan-black",
    },
    {
        "id": "titan-z",
        "name": "NVIDIA GeForce GTX Titan Z",
        "short_name": "GTX Titan Z",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-titan-z.c2575",
        "tpu_id": "c2575",
        # Dual-GPU: board totals override the per-GPU live page (see GTX 690).
        "tpu_overrides": {"cuda_cores": 5760, "tmu": 480, "rop": 96,
                          "pixel_rate_gpixels": 105.12, "texture_rate_gtexels": 420.4,
                          "theoretical_fp32_tflops": 10.092,
                          "theoretical_fp64_gflops": 3364.0,
                          "transistors_b": 14.16, "die_size_mm2": 1122,
                          "die": "2x GK110-350-B1", "memory_size_gb": 12},
        "shs_slug": "geforce-gtx-titan-z",
        "shs_url": "https://secondhandsilicon.com/product/geforce-gtx-titan-z",
    },
    {
        "id": "titan-x-maxwell",
        "name": "NVIDIA GeForce GTX Titan X",
        "short_name": "GTX Titan X",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/geforce-gtx-titan-x.c2632",
        "tpu_id": "c2632",
        "shs_slug": "geforce-gtx-titan-x",
        "shs_url": "https://secondhandsilicon.com/product/geforce-gtx-titan-x",
    },
    {
        "id": "titan-xp",
        "name": "NVIDIA Titan Xp",
        "short_name": "Titan Xp",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/titan-xp.c2948",
        "tpu_id": "c2948",
        # Listings may mix TITAN X (Pascal) cards (sellers confuse them);
        # titles archived for later splits.
        "shs_slug": "geforce-gtx-titan-xp",
        "shs_url": "https://secondhandsilicon.com/product/geforce-gtx-titan-xp",
    },
    {
        "id": "titan-rtx",
        "name": "NVIDIA Titan RTX",
        "short_name": "Titan RTX",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/titan-rtx.c3311",
        "tpu_id": "c3311",
        "shs_slug": "geforce-rtx-titan",
        "shs_url": "https://secondhandsilicon.com/product/geforce-rtx-titan",
    },
    # ---- Radeon RX XT refreshes + RDNA1/4 fill-ins. 9060 XT SHS slug
    # aggregates 16GB+8GB; TPU ref is the 16GB launch page.
    {
        "id": "rx-5500-xt",
        "name": "AMD Radeon RX 5500 XT",
        "short_name": "RX 5500 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-5500-xt.c3468",
        "tpu_id": "c3468",
        "shs_slug": "amd-rx-5500-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-5500-xt",
    },
    {
        "id": "rx-5600-xt",
        "name": "AMD Radeon RX 5600 XT",
        "short_name": "RX 5600 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-5600-xt.c3474",
        "tpu_id": "c3474",
        "shs_slug": "amd-rx-5600-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-5600-xt",
    },
    {
        "id": "rx-6500-xt",
        "name": "AMD Radeon RX 6500 XT",
        "short_name": "RX 6500 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6500-xt.c3850",
        "tpu_id": "c3850",
        "shs_slug": "amd-rx-6500-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6500-xt",
    },
    {
        "id": "rx-6600-xt",
        "name": "AMD Radeon RX 6600 XT",
        "short_name": "RX 6600 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6600-xt.c3774",
        "tpu_id": "c3774",
        "shs_slug": "amd-rx-6600-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6600-xt",
    },
    {
        "id": "rx-6650-xt",
        "name": "AMD Radeon RX 6650 XT",
        "short_name": "RX 6650 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6650-xt.c3898",
        "tpu_id": "c3898",
        "shs_slug": "amd-rx-6650-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6650-xt",
    },
    {
        "id": "rx-6700-xt",
        "name": "AMD Radeon RX 6700 XT",
        "short_name": "RX 6700 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6700-xt.c3695",
        "tpu_id": "c3695",
        "shs_slug": "amd-rx-6700-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6700-xt",
    },
    {
        "id": "rx-6750-xt",
        "name": "AMD Radeon RX 6750 XT",
        "short_name": "RX 6750 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6750-xt.c3879",
        "tpu_id": "c3879",
        "shs_slug": "amd-rx-6750-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6750-xt",
    },
    {
        "id": "rx-6800-xt",
        "name": "AMD Radeon RX 6800 XT",
        "short_name": "RX 6800 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6800-xt.c3694",
        "tpu_id": "c3694",
        "shs_slug": "amd-rx-6800-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6800-xt",
    },
    {
        "id": "rx-6900-xt",
        "name": "AMD Radeon RX 6900 XT",
        "short_name": "RX 6900 XT",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-6900-xt.c3481",
        "tpu_id": "c3481",
        "shs_slug": "amd-rx-6900-xt",
        "shs_url": "https://secondhandsilicon.com/product/amd-rx-6900-xt",
    },
    {
        "id": "rx-9060-xt",
        "name": "AMD Radeon RX 9060 XT",
        "short_name": "RX 9060 XT",
        "relperf_name": "Radeon RX 9060 XT 16 GB",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-rx-9060-xt-16-gb.c4293",
        "tpu_id": "c4293",
        "shs_slug": "radeon-rx-9060-xt",
        "shs_url": "https://secondhandsilicon.com/product/radeon-rx-9060-xt",
    },
    # ---- Quadro Kepler (Kx000/Kx200). TPU IDs via websearch snippets.
    {
        "id": "quadro-k2000",
        "name": "NVIDIA Quadro K2000",
        "short_name": "Quadro K2000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-k2000.c1838",
        "tpu_id": "c1838",
        "shs_slug": "quadro-k2000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-k2000",
    },
    {
        "id": "quadro-k2200",
        "name": "NVIDIA Quadro K2200",
        "short_name": "Quadro K2200",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-k2200.c2601",
        "tpu_id": "c2601",
        "shs_slug": "quadro-k2200",
        "shs_url": "https://secondhandsilicon.com/product/quadro-k2200",
    },
    {
        "id": "quadro-k4200",
        "name": "NVIDIA Quadro K4200",
        "short_name": "Quadro K4200",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-k4200.c2602",
        "tpu_id": "c2602",
        "shs_slug": "quadro-k4200",
        "shs_url": "https://secondhandsilicon.com/product/quadro-k4200",
    },
    {
        "id": "quadro-k5200",
        "name": "NVIDIA Quadro K5200",
        "short_name": "Quadro K5200",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-k5200.c2603",
        "tpu_id": "c2603",
        "shs_slug": "quadro-k5200",
        "shs_url": "https://secondhandsilicon.com/product/quadro-k5200",
    },
    {
        "id": "quadro-k6000",
        "name": "NVIDIA Quadro K6000",
        "short_name": "Quadro K6000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-k6000.c2426",
        "tpu_id": "c2426",
        "shs_slug": "quadro-k6000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-k6000",
    },
    # ---- Quadro Maxwell (Mx000).
    {
        "id": "quadro-m2000",
        "name": "NVIDIA Quadro M2000",
        "short_name": "Quadro M2000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-m2000.c2837",
        "tpu_id": "c2837",
        "shs_slug": "quadro-m2000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-m2000",
    },
    {
        "id": "quadro-m4000",
        "name": "NVIDIA Quadro M4000",
        "short_name": "Quadro M4000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-m4000.c2757",
        "tpu_id": "c2757",
        "shs_slug": "quadro-m4000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-m4000",
    },
    {
        "id": "quadro-m5000",
        "name": "NVIDIA Quadro M5000",
        "short_name": "Quadro M5000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-m5000.c2756",
        "tpu_id": "c2756",
        "shs_slug": "quadro-m5000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-m5000",
    },
    {
        "id": "quadro-m6000",
        "name": "NVIDIA Quadro M6000",
        "short_name": "Quadro M6000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-m6000.c2638",
        "tpu_id": "c2638",
        "shs_slug": "quadro-m6000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-m6000",
    },
    # ---- Quadro Pascal (Px000).
    {
        "id": "quadro-p400",
        "name": "NVIDIA Quadro P400",
        "short_name": "Quadro P400",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-p400.c2934",
        "tpu_id": "c2934",
        "shs_slug": "quadro-p400",
        "shs_url": "https://secondhandsilicon.com/product/quadro-p400",
    },
    {
        "id": "quadro-p2000",
        "name": "NVIDIA Quadro P2000",
        "short_name": "Quadro P2000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-p2000.c2931",
        "tpu_id": "c2931",
        "shs_slug": "quadro-p2000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-p2000",
    },
    {
        "id": "quadro-p5000",
        "name": "NVIDIA Quadro P5000",
        "short_name": "Quadro P5000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-p5000.c2864",
        "tpu_id": "c2864",
        "shs_slug": "quadro-p5000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-p5000",
    },
    # ---- Quadro Turing RTX 5000.
    {
        "id": "quadro-rtx-5000",
        "name": "NVIDIA Quadro RTX 5000",
        "short_name": "Quadro RTX 5000",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/quadro-rtx-5000.c3308",
        "tpu_id": "c3308",
        "shs_slug": "quadro-rtx-5000",
        "shs_url": "https://secondhandsilicon.com/product/quadro-rtx-5000",
    },
    # ---- Tesla Kepler/Maxwell/Pascal (K80 is dual-GPU, board totals).
    {
        "id": "tesla-k80",
        "name": "NVIDIA Tesla K80",
        "short_name": "Tesla K80",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/tesla-k80.c2616",
        "tpu_id": "c2616",
        "tpu_overrides": {"cuda_cores": 4992, "tmu": 416, "rop": 96,
                          "pixel_rate_gpixels": 85.7, "texture_rate_gtexels": 342.8,
                          "theoretical_fp32_tflops": 8.226,
                          "theoretical_fp64_gflops": 2742.0,
                          "transistors_b": 14.2, "die_size_mm2": 1212,
                          "die": "2x GK210-885-A1", "memory_size_gb": 24},
        "shs_slug": "tesla-k80",
        "shs_url": "https://secondhandsilicon.com/product/tesla-k80",
    },
    {
        "id": "tesla-m40",
        "name": "NVIDIA Tesla M40",
        "short_name": "Tesla M40",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/tesla-m40.c2771",
        "tpu_id": "c2771",
        "shs_slug": "tesla-m40",
        "shs_url": "https://secondhandsilicon.com/product/tesla-m40",
    },
    {
        "id": "tesla-p40",
        "name": "NVIDIA Tesla P40",
        "short_name": "Tesla P40",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/tesla-p40.c2878",
        "tpu_id": "c2878",
        "shs_slug": "tesla-p40",
        "shs_url": "https://secondhandsilicon.com/product/tesla-p40",
    },
    # ---- Radeon HD 5000/6000/7000/8000 (TeraScale/GCN; Theoretical
    # fallback). TPU IDs via websearch snippets. 7870/7770 refs are the GHz
    # Editions (launch configs); 7970 ref is the launch card (GHz Edition
    # exists separately); 8570 ref is the OEM page.
    {
        "id": "hd-5570",
        "name": "AMD Radeon HD 5570",
        "short_name": "HD 5570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-5570.c3265",
        "tpu_id": "c3265",
        "shs_slug": "radeon-hd-5570",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-5570",
    },
    {
        "id": "hd-6570",
        "name": "AMD Radeon HD 6570",
        "short_name": "HD 6570",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6570.c277",
        "tpu_id": "c277",
        "shs_slug": "radeon-hd-6570",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6570",
    },
    {
        "id": "hd-6670",
        "name": "AMD Radeon HD 6670",
        "short_name": "HD 6670",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6670.c406",
        "tpu_id": "c406",
        "shs_slug": "radeon-hd-6670",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6670",
    },
    {
        "id": "hd-6750",
        "name": "AMD Radeon HD 6750",
        "short_name": "HD 6750",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6750.c279",
        "tpu_id": "c279",
        "shs_slug": "radeon-hd-6750",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6750",
    },
    {
        "id": "hd-6770",
        "name": "AMD Radeon HD 6770",
        "short_name": "HD 6770",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6770.c280",
        "tpu_id": "c280",
        "shs_slug": "radeon-hd-6770",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6770",
    },
    {
        "id": "hd-6790",
        "name": "AMD Radeon HD 6790",
        "short_name": "HD 6790",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6790.c283",
        "tpu_id": "c283",
        "shs_slug": "radeon-hd-6790",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6790",
    },
    {
        "id": "hd-6950",
        "name": "AMD Radeon HD 6950",
        "short_name": "HD 6950",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6950.c405",
        "tpu_id": "c405",
        "shs_slug": "radeon-hd-6950",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6950",
    },
    {
        "id": "hd-6970",
        "name": "AMD Radeon HD 6970",
        "short_name": "HD 6970",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-6970.c258",
        "tpu_id": "c258",
        "shs_slug": "radeon-hd-6970",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-6970",
    },
    {
        "id": "hd-7770",
        "name": "AMD Radeon HD 7770",
        "short_name": "HD 7770",
        "relperf_name": "Radeon HD 7770 GHz Edition",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-7770-ghz-edition.c308",
        "tpu_id": "c308",
        "shs_slug": "radeon-hd-7770",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-7770",
    },
    {
        "id": "hd-7870",
        "name": "AMD Radeon HD 7870",
        "short_name": "HD 7870",
        "relperf_name": "Radeon HD 7870 GHz Edition",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-7870-ghz-edition.c339",
        "tpu_id": "c339",
        "shs_slug": "radeon-hd-7870",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-7870",
    },
    {
        "id": "hd-7950",
        "name": "AMD Radeon HD 7950",
        "short_name": "HD 7950",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-7950.c307",
        "tpu_id": "c307",
        "shs_slug": "radeon-hd-7950",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-7950",
    },
    {
        "id": "hd-7970",
        "name": "AMD Radeon HD 7970",
        "short_name": "HD 7970",
        # Launch card (925 MHz); GHz Edition (c365) exists separately and
        # shares the used market (titles archived).
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-7970.c296",
        "tpu_id": "c296",
        "shs_slug": "radeon-hd-7970",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-7970",
    },
    {
        "id": "hd-8570",
        "name": "AMD Radeon HD 8570",
        "short_name": "HD 8570",
        # OEM-only card; TPU reference is the OEM page.
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-8570-oem.c1974",
        "tpu_id": "c1974",
        "shs_slug": "radeon-hd-8570",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-8570",
    },
    # ---- Radeon R9 200/300 (GCN; Theoretical fallback).
    {
        "id": "r9-290",
        "name": "AMD Radeon R9 290",
        "short_name": "R9 290",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-290.c2397",
        "tpu_id": "c2397",
        "shs_slug": "amd-r9-290",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-290",
    },
    {
        "id": "r9-290x",
        "name": "AMD Radeon R9 290X",
        "short_name": "R9 290X",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-290x.c2460",
        "tpu_id": "c2460",
        "shs_slug": "amd-r9-290x",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-290x",
    },
    {
        "id": "r9-390",
        "name": "AMD Radeon R9 390",
        "short_name": "R9 390",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-390.c2664",
        "tpu_id": "c2664",
        "shs_slug": "amd-r9-390",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-390",
    },
    {
        "id": "r9-390x",
        "name": "AMD Radeon R9 390X",
        "short_name": "R9 390X",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-390x.c2663",
        "tpu_id": "c2663",
        "shs_slug": "amd-r9-390x",
        "shs_url": "https://secondhandsilicon.com/product/amd-r9-390x",
    },
    # ---- Dual-GPU flagships (board totals via tpu_overrides, see GTX 690).
    {
        "id": "hd-7990",
        "name": "AMD Radeon HD 7990",
        "short_name": "HD 7990",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-hd-7990.c2126",
        "tpu_id": "c2126",
        "tpu_overrides": {"cuda_cores": 4096, "tmu": 256, "rop": 64,
                          "pixel_rate_gpixels": 64.0, "texture_rate_gtexels": 256.0,
                          "theoretical_fp32_tflops": 8.192,
                          "theoretical_fp64_gflops": 2048.0,
                          "transistors_b": 8.62, "die_size_mm2": 730,
                          "die": "2x Malta XT (215-0849026)", "memory_size_gb": 6},
        "shs_slug": "radeon-hd-7990",
        "shs_url": "https://secondhandsilicon.com/product/radeon-hd-7990",
    },
    {
        "id": "r9-295x2",
        "name": "AMD Radeon R9 295X2",
        "short_name": "R9 295X2",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/radeon-r9-295x2.c2523",
        "tpu_id": "c2523",
        "tpu_overrides": {"cuda_cores": 5632, "tmu": 352, "rop": 128,
                          "pixel_rate_gpixels": 130.3, "texture_rate_gtexels": 358.4,
                          "theoretical_fp32_tflops": 11.466,
                          "theoretical_fp64_gflops": 1433.4,
                          "transistors_b": 12.4, "die_size_mm2": 876,
                          "die": "2x Vesuvius XT (215-0852022)", "memory_size_gb": 8},
        "shs_slug": "radeon-r9-295x2",
        "shs_url": "https://secondhandsilicon.com/product/radeon-r9-295x2",
    },
    # ---- Workstation Ampere RTX A4500.
    {
        "id": "rtx-a4500",
        "name": "NVIDIA RTX A4500",
        "short_name": "RTX A4500",
        "tpu_url": "https://www.techpowerup.com/gpu-specs/rtx-a4500.c3849",
        "tpu_id": "c3849",
        "shs_slug": "rtx-a4500",
        "shs_url": "https://secondhandsilicon.com/product/rtx-a4500",
    },
]
